[config]
# command = "notify-send"
# arguments = [""]
# set = false


[templates.hyprland]
input_path = './templates/hyprland.conf'
output_path = '~/.config/hypr/theme.conf'

[templates.ghostty]
input_path = './templates/ghostty.theme'
output_path = '~/.config/ghostty/themes/matugen'
# INFO: Enable this only when using ghostty release version of at least 1.14 (not out yet)
# post_hook = 'killall -SIGUSR2 ghostty || true'

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/theme.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/theme.conf'

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = "pkill -USR1 cava || true"

[templates.zathura]
input_path = './templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

# [templates.fuzzel]
# input_path = './templates/fuzzel.ini'
# output_path = '~/.config/fuzzel/colors.ini'
