[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:charging1948/nvim_dots.git"
    refreshPeriod = "24h"
    [".config/nvim".pull]
        args = ["--ff-only"]

[".config/ags"]
    type = "git-repo"
    url = "git@github.com:charging1948/ags-flake.git"
    refreshPeriod = "24h"
    [".config/ags".pull]
        args = ["--ff-only"]