# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         User Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

input {
  kb_layout = de
  kb_variant = nodeadkeys
}


cursor {
  no_hardware_cursors = 1
}

render {
  direct_scanout = 2
  cm_fs_passthrough = 2
}

quirks {
  prefer_hdr = 1
}

