# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         User Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

input {
  kb_layout = de
  kb_variant = nodeadkeys
}


cursor {
  no_hardware_cursors = 1
}

render {
  direct_scanout = 1
  non_shader_cm = 3
  # keep_unmodified_copy = 1
}

quirks {
  prefer_hdr = 1
}


